/*
 * Copyright (c) 2025 HPMicro, All Rights Reserved
 * 
 * SPDX-License-Identifier: BSD-3-Clause
 * 
 */
#ifndef APPLICATIONS_GW_MQ_MSG_H_
#define APPLICATIONS_GW_MQ_MSG_H_

typedef struct
{
    uint16_t msg_id;
    uint16_t submsg_id;
    uint32_t param;
    void*    user_data;
} gw_mq_msg;

typedef gw_mq_msg* gw_mq_msg_t;

typedef enum
{
    GW_MQ_MSG_MISC_BASE_ID  = 0,
    GW_MQ_MSG_MISC_LED_ID,
    GW_MQ_MSG_MISC_TIMER_ID,
    GW_MQ_MSG_MISC_KEY_ID,
    GW_MQ_MSG_LCD_ID,
    GW_MQ_MSG_ECAT_ID,
    GW_MQ_MSG_MAX_ID
}gw_mq_msg_id_e;

typedef enum
{
    GW_MQ_SUBMSG_MISC_LED_BASE_ID  = 0,
    GW_MQ_SUBMSG_MISC_LED_DEV_STATE_INIT_ID,
    GW_MQ_SUBMSG_MISC_LED_DEV_STATE_BOOTSTRAP_ID,
    GW_MQ_SUBMSG_MISC_LED_DEV_STATE_PRE_OP_ID,
    GW_MQ_SUBMSG_MISC_LED_DEV_STATE_SAFE_OP_ID,
    GW_MQ_SUBMSG_MISC_LED_DEV_STATE_OP_ID,
    GW_MQ_SUBMSG_MISC_LED_DEV_STATE_FAIL_ID,
    GW_MQ_SUBMSG_MISC_LED_CAN_STATE_TX_OK_ID,
    GW_MQ_SUBMSG_MISC_LED_CAN_STATE_RX_OK_ID,
    GW_MQ_SUBMSG_MISC_LED_MAX_ID
}gw_mq_submsg_misc_led_id_e;

typedef enum
{
    GW_MQ_SUBMSG_MISC_TIMER_BASE_ID  = 0,
    GW_MQ_SUBMSG_MISC_TIMER_1MS_ID,
    GW_MQ_SUBMSG_MISC_TIMER_10MS_ID,
    GW_MQ_SUBMSG_MISC_TIMER_100MS_ID,
    GW_MQ_SUBMSG_MISC_TIMER_1000MS_ID,    
    GW_MQ_SUBMSG_MISC_TIMER_MAX_ID
}gw_mq_submsg_misc_timer_id_e;

typedef enum
{
    GW_MQ_SUBMSG_MISC_KEY_BASE_ID  = 0,
    GW_MQ_SUBMSG_MISC_KEY_A_PRESS_ID, 
    GW_MQ_SUBMSG_MISC_KEY_A_LONG_PRESS_ID, 
    GW_MQ_SUBMSG_MISC_KEY_B_PRESS_ID,    
    GW_MQ_SUBMSG_MISC_KEY_B_LONG_PRESS_ID, 
    GW_MQ_SUBMSG_MISC_KEY_C_PRESS_ID,    
    GW_MQ_SUBMSG_MISC_KEY_C_LONG_PRESS_ID,    
    GW_MQ_SUBMSG_MISC_KEY_D_PRESS_ID,       
    GW_MQ_SUBMSG_MISC_KEY_D_LONG_PRESS_ID,    
    GW_MQ_SUBMSG_MISC_KEY_MAX_ID
}gw_mq_submsg_misc_key_id_e;

typedef enum
{
    GW_MQ_SUBMSG_LCD_BASE_ID  = 0,
    GW_MQ_SUBMSG_LCD_UPDATE_ID,
    GW_MQ_SUBMSG_LCD_KEYA_CLICKED_ID,
    GW_MQ_SUBMSG_LCD_KEYA_LONG_CLICKED_ID,
    GW_MQ_SUBMSG_LCD_KEYB_CLICKED_ID,
    GW_MQ_SUBMSG_LCD_KEYB_LONG_CLICKED_ID,
    GW_MQ_SUBMSG_LCD_KEYC_CLICKED_ID,
    GW_MQ_SUBMSG_LCD_KEYC_LONG_CLICKED_ID,
    GW_MQ_SUBMSG_LCD_KEYD_CLICKED_ID,
    GW_MQ_SUBMSG_LCD_KEYD_LONG_CLICKED_ID,
    GW_MQ_SUBMSG_LCD_SET_SLAVES_NUM_ID,
    GW_MQ_SUBMSG_LCD_SET_STATE_ID,
    GW_MQ_SUBMSG_LCD_SET_TXNUM_ID,
    GW_MQ_SUBMSG_LCD_SET_RXNUM_ID,
    GW_MQ_SUBMSG_LCD_SET_START_ID,
    GW_MQ_SUBMSG_LCD_SET_STOP_ID,
    GW_MQ_SUBMSG_LCD_MAX_ID
}gw_mq_submsg_lcd_id_e;
typedef enum
{
    GW_MQ_SUBMSG_ECAT_BASE_ID  = 0,
    GW_MQ_SUBMSG_ECAT_UPDATE_ID,
    GW_MQ_SUBMSG_ECAT_START_ID,
    GW_MQ_SUBMSG_ECAT_STOP_ID,
    GW_MQ_SUBMSG_ECAT_SET_CAN_BAUDRATE_ID,
    GW_MQ_SUBMSG_ECAT_SET_MODE_ID,
    GW_MQ_SUBMSG_ECAT_SET_TRIGGER_ID,
    GW_MQ_SUBMSG_ECAT_SET_CYCLE_TIME_ID,
    GW_MQ_SUBMSG_ECAT_SET_FRAME_MODE_ID,
    GW_MQ_SUBMSG_ECAT_MAX_ID
}gw_mq_submsg_ecat_id_e;



#endif /* APPLICATIONS_GW_MQ_MSG_H_ */
