
/*
 * Copyright (c) 2025 HPMicro
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 *
 * Automatically generated by HPM Pinmux Tool
 *
 *
 * Note:
 * PY and PZ IOs: if any SOC pin function needs to be routed to these IOs,
 * besides of IOC, PIOC/BIOC needs to be configured SOC_GPIO_X_xx, so that
 * expected SoC function can be enabled on these IOs.
 */

#ifndef HPM_PINMUX_H
#define HPM_PINMUX_H

#ifdef __cplusplus
extern "C" {
#endif

void init_uart0_pins(void);
void init_uart2_pins(void);
void init_uart13_pins(void);
void init_puart_pins(void);
void init_uart13_pins_as_gpio(void);
void init_femc_pins(void);
void init_gpio_pins_with_pull_up(void);
void init_gpio_pins_using_gpio0(void);
void init_enet0_pins(void);
void init_enet1_pins(void);
void init_usb0_pins(void);
void init_usb1_pins(void);
void init_sdxc1_cmd_pin_enable_1v8_enable_opendrain(void);
void init_sdxc1_cmd_pin_enable_1v8_disable_opendrain(void);
void init_sdxc1_cmd_pin_disable_1v8_enable_opendrain(void);
void init_sdxc1_cmd_pin_disable_1v8_disable_opendrain(void);
void init_sdxc1_cd_pin(void);
void init_sdxc1_clk_data_pins_enable_1v8(void);
void init_sdxc1_clk_data_pins_disable_1v8(void);
void init_sdxc1_clk_data_pins_width4_enable_1v8(void);
void init_sdxc1_clk_data_pins_width4_disable_1v8(void);
void init_sdxc1_pwr_pin(void);
void init_enet_pps_pins(void);
void init_enet_pps_capture_pins(void);

#ifdef __cplusplus
}
#endif
#endif /* HPM_PINMUX_H */
